version: '3.5'

services:
  c2id:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./conf/c2id:/etc/c2id
    ports:
      - "8080:8080"
    network_mode: host
#    networks:
#      professos_default:
#        aliases:
#          - honest-idp.com
#          - honest-sp.com

networks:
  professos_default:
    external:
      name: professos-default-net


