version: "3.6"

services:
  professos:
    build:
      context: ./professos
      args:
        gitbranch: development
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        CONTROLLER_HOST: openid.professos
        HONEST_OP_HOST: honest-idp.professos
        EVIL_OP_HOST: attack-idp.professos
        HONEST_RP_HOST: rp.professos
        EVIL_RP_HOST: evilrp.professos
        TEST_RP_HOST: mitreid-client
        TEST_OP_HOST: mitreid-server
    environment:
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    networks:
      profnet:
        aliases:
          - openid.professos
          - honest-idp.professos
          - rp.professos
          - attack-idp.professos
          - evilrp.professos

  nginx-proxy-mitm:
    command: mitmweb --web-iface 0.0.0.0 --set web_open_browser=false --ssl-insecure
    dns:
      - 127.0.0.1
    image: artemkloko/mitm-nginx-proxy-companion
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - idpnet
      - rpnet
      - profnet

  nginx-proxy:
    depends_on:
      - certs
    image: jwilder/nginx-proxy
    labels:
      - "mitmproxy.proxyVirtualHosts=true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: professos
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    networks:
      - profnet


  certs:
    environment:
      - CA_CERT=/certs/self-signed.crt
      - CA_KEY=/certs/self-signed.key
      - CA_EXPIRE=3650
      - SSL_SIZE=2048
    image: paulczar/omgwtfssl
    volumes:
      - certs:/certs

  mitreid-server:
    build:
      context: ./idp/mitreid-server
      args:
        CONTROLLER_URL: openid.professos
    environment:
      VIRTUAL_HOST: mitreid-server
      #VIRTUAL_PORT: 8080
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    networks:
      - idpnet

  mitreid-client:
    build:
      context: ./rp/mitreid-client
      args:
        CONTROLLER_URL: openid.professos
    environment:
      VIRTUAL_HOST: mitreid-client
      #VIRTUAL_PORT: 8080
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    networks:
      - rpnet

networks:
  profnet:
    driver: bridge
  idpnet:
    internal: true
  rpnet:
    internal: true

volumes:
  certs:
