version: "3.6"

services:
  certs:
    build:
      context: ./oidc-cert
    environment:
      - CA_KEY=oidc-ca.key
      - CA_EXPIRE=3650
      - SSL_KEY_SIZE=2048
    env_file:
      - ".env"
    volumes:
      - certs:/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mitmproxy:
    build:
      context: ./mitmproxy
    depends_on:
      - certs
    environment:
      - CA_DIR=${CA_DIR}
      - CA_CERT=${CA_CERT}
      - CA_KEY=${CA_KEY}
    dns:
      - 127.0.0.1
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./mitmproxy/scripts:/home/mitmproxy/scripts
      - certs:/certs:ro
    networks:
      - idpnet
      - rpnet
      - profnet

  professos:
    build:
      context: ./professos
      args:
        gitbranch: development
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        DISABLE_TLS_TRUST_CHECK: "true"
        CA_CERT: ${CA_CERT}
        CONTROLLER_HOST: ${CONTROLLER_HOST}
        HONEST_OP_HOST: ${HONEST_OP_HOST}
        EVIL_OP_HOST: ${EVIL_OP_HOST}
        HONEST_RP_HOST: ${HONEST_RP_HOST}
        EVIL_RP_HOST: ${EVIL_RP_HOST}
        TEST_RP_HOST: ${MITREID_CLIENT_HOST}
        TEST_OP_HOST: ${MITREID_SERVER_HOST}
    environment:
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
    env_file:
      - .proxy_env
    depends_on:
      - certs
    ports:
      - "9990:9990"   # enable management interface
      - "8888:8080"   # web interface
      - "8787:8787"   # debugging interface
    volumes:
      - certs:/certs:ro
    networks:
      profnet:
        aliases:
          - ${CONTROLLER_HOST}
          - ${HONEST_OP_HOST}
          - ${EVIL_OP_HOST}
          - ${HONEST_RP_HOST}
          - ${EVIL_RP_HOST}

########################################################################################################################
# IdP
########################################################################################################################

  mitreid-server:
    build:
      context: ./idp/mitreid-server
      args:
        BRANCH: "mitreid-connect-1.3.3"
        ISSUER: ${MITREID_SERVER_HOST}
        MITREID_SERVER_HOST: ${MITREID_SERVER_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
    depends_on:
      - certs
    volumes:
      - certs:/certs:ro
    env_file:
      - .proxy_env
    environment:
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${MITREID_SERVER_HOST}
    networks:
      - idpnet

  identity-server4:
    build:
      context: ./idp/identity-server4
      args:
        BRANCH: "3.1.2"
        ISSUER: ${IDENTITY_SERVER4_HOST}
        SERVER_HOST: ${IDENTITY_SERVER4_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
    depends_on:
      - certs
    volumes:
      - certs:/certs:ro
    env_file:
      - .proxy_env
    environment:
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${IDENTITY_SERVER4_HOST}
    networks:
      - idpnet

###
# Keycloak
###
  keycloak:
    build:
      context: ./idp/keycloak
      args:
        SERVER_HOST: ${KEYCLOAK_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 4dm1n
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${KEYCLOAK_HOST}
    depends_on:
      - keycloak-postgres
      - certs
    volumes:
      - certs:/certs:ro
    env_file:
      - .proxy_env
    networks:
      - idpnet

  keycloak-postgres:
    image: postgres:11
    volumes:
    -  ./idp/keycloak/config/keycloak.sql:/docker-entrypoint-initdb.d/keycloak-code.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - idpnet

###
# Gravitee.io
##

  gravitee:
    build:
      context: ./idp/gravitee
      dockerfile: Dockerfile.nginx
      args:
        SERVER_HOST: ${GRAVITEE_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
    volumes:
      - certs:/certs:ro
    environment:
      NGINX_PORT: 80
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${GRAVITEE_HOST}
    depends_on:
      - gravitee-management
      - gravitee-gateway
      - gravitee-webui
      - certs
    networks:
      - idpnet

  gravitee-mongodb:
    image: mongo:3.4
    volumes:
      - ./idp/gravitee/logs/am-mongodb:/var/log/mongodb
    networks:
      - idpnet

  gravitee-mongo-seed:
    build:
      context: ./idp/gravitee
      dockerfile: Dockerfile.mongo
    links:
      - gravitee-mongodb
    networks:
      - idpnet

  gravitee-gateway:
    image: graviteeio/am-gateway:${GIO_AM_VERSION}
    links:
      - gravitee-mongodb
    depends_on:
      - gravitee-mongodb
    volumes:
      - ./idp/gravitee/logs/am-gateway:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://gravitee-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://gravitee-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    networks:
      - idpnet

  gravitee-management:
    image: graviteeio/am-management-api:${GIO_AM_VERSION}
    links:
      - gravitee-mongodb
    depends_on:
      - gravitee-mongodb
    volumes:
      - ./idp/gravitee/logs/am-management-api:/etc/gravitee.io/log
    environment:
      - gravitee_management_mongodb_uri=mongodb://gravitee-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_oauth2_mongodb_uri=mongodb://gravitee-mongodb:27017/graviteeam?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
    networks:
      - idpnet

  gravitee-webui:
    image: graviteeio/am-management-ui:${GIO_AM_VERSION}
    depends_on:
      - gravitee-management
    environment:
      - MGMT_API_URL=https://gravitee/am
      - MGMT_UI_URL=https://gravitee/am/ui
    volumes:
      - ./idp/gravitee/logs/am-webui:/var/log/httpd
    networks:
      - idpnet

########################################################################################################################
# RP
########################################################################################################################

  mitreid-client:
    build:
      context: ./rp/mitreid-client
      args:
        ISSUER: ${HONEST_OP_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
        MITREID_CLIENT_HOST: ${MITREID_CLIENT_HOST}
    depends_on:
      - certs
    volumes:
      - certs:/certs:ro
    env_file:
      - .proxy_env
    environment:
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${MITREID_CLIENT_HOST}
    networks:
      - rpnet

  angular-auth-oidc-client:
    build:
      context: ./rp/angular-auth-oidc-sample-client
      args:
        ISSUER: ${HONEST_OP_HOST}
        CONTROLLER_URL: ${CONTROLLER_HOST}
        CLIENT_HOST: ${ANGULAR_AUTH_CLIENT_HOST}
    depends_on:
      - certs
    volumes:
      - certs:/certs:ro
    env_file:
      - .proxy_env
    environment:
      CA_DIR: ${CA_DIR}
      CA_CERT: ${CA_CERT}
      VIRTUAL_HOST: ${ANGULAR_AUTH_CLIENT_HOST}
    networks:
      - rpnet

########################################################################################################################
# Networks & Volumes
########################################################################################################################
networks:
  profnet:
    name: profnet
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: oidc-profnet
  idpnet:
    name: idpnet
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.name: oidc-idpnet
  rpnet:
    name: rpnet
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.name: oidc-rpnet

volumes:
  certs:
