version: '3.5'

services:
  mitre_sp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    networks:
      professos_default:
        aliases:
          - honestsp.de
          - www.honestsp.de

networks:
  professos_default:
    external:
      name: professos-default-net

