FROM nginx:1.17.10-alpine

RUN apk update \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*

ARG CONTROLLER_URL
ARG SERVER_HOST

ARG CA_DIR="/certs"
ARG CA_CERT="oidc-ca.crt"
VOLUME ["$CA_DIR"]

COPY config/nginx.conf /etc/nginx/nginx.conf
RUN sed -i "s#SERVER_HOST#$SERVER_HOST#g" /etc/nginx/nginx.conf

RUN echo "https://$CONTROLLER_URL" > /usr/share/nginx/html/.professos

EXPOSE 80
EXPOSE 443

COPY docker-entrypoint.sh /docker-entrypoint.sh

CMD ["/docker-entrypoint.sh"]
