version: '3.5'

services:
  maoidc:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80"
    networks:
      professos_default:
        aliases:
          - honestsp.de
          - www.honestsp.de

networks:
  professos_default:
    external:
      name: professos-default-net

