version: '3.5'

services:
  ruby_rp:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"
    networks:
      professos_default:
        aliases:
          - honest-sp.com
          - www.honest-sp.com

networks:
  professos_default:
    external:
      name: professos-default-net
